name: Create vercel preview URL on pull request
on:
  pull_request:
    branches:
      - main
  push: # Added to trigger on commits
    branches:
      - main # Or other branches you want to deploy on push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}  addhere to promote to production in vercel and give me update code
